name: Deploy PostgreSQL to oracleK8S

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCI CLI
        uses: oracle/oci-cli-action@v2
        with:
          oci-cli-version: 'latest'

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=${{ secrets.OCI_PRIVATE_KEY }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config

      - name: Set up kubectl
        run: |
          oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OCI_CLUSTER_OCID }} --file ~/.kube/config --region ${{ secrets.OCI_REGION }}

      - name: Deploy PostgreSQL to OKE
        run: |
          kubectl apply -f k8s/postgresql-deployment.yml
          kubectl apply -f k8s/postgresql-service.yml
